### ISSUE TITLE
Instructions for authors to update their zenodo badge

### ISSUE THREAD

**Issue by negin513** [UCAR-SEA/SEA-ISS-Template#1]

**Comment by kafitzgerald** [comment]
Project Pythia has some instructions for doing this here: https://github.com/ProjectPythia/.github/blob/main/.github/CONTRIBUTING.md#make-a-zenodo-release-of-your-cookbook

A couple of things to note:
* It looks like this happens after transferring repository ownership to the Project Pythia org so the repo URL/org is correct in Zenodo.  There's an open issue (zenodo/zenodo#1653) over on the Zenodo repo about handling this situation and it's not clear that it's smooth.  If we're going to have folks transfer ownership to SEA, I think setting up DOIs w/ Zenodo after probably makes the most sense.
* The instructions for this are a bit new so we may want to test this out first or update after walking the first person through.

**Comment by kafitzgerald** [comment]
I can add something to the instructions in the repo about this later today or tomorrow morning.

**Comment by negin513** [comment]
Hi @kafitzgerald I added this bit about Zenodo DOI badge last night:
https://ucar-sea.github.io/SEA-ISS-Template/submission-guidelines.html#make-zenodo-doi-for-your-paper

Does this address it?

**Comment by negin513** [comment]
We also need to update this page: 
https://ucar-sea.github.io/SEA-ISS-Template/how-to-cite-this-paper.html

**Comment by kafitzgerald** [comment]
Sorry, I missed this.  Yes, absolutely!  

Seems like the only remaining bit is to include some info on how to update their paper with the new DOI / citation info and that page you mentioned.

**Comment by kafitzgerald** [comment]
Looks like this is done now (probably a while back).
